# tox.ini
[tox]
envlist = pre-commit,mypy,min,py310,py311,py312,py313,docs

[testenv]
deps =
    pytest
    pytest-cov
commands =
    py.test --doctest-modules --cov=scrapy_zyte_smartproxy --cov-report term-missing {posargs:scrapy_zyte_smartproxy tests}

[testenv:pre-commit]
deps = pre-commit
commands = pre-commit run --all-files --show-diff-on-failure
skip_install = true

[testenv:mypy]
basepython = python3.10
deps =
    mypy==1.20.2
    pytest
commands =
    mypy {posargs:scrapy_zyte_smartproxy tests}

[testenv:min]
basepython = python3.10
deps =
    {[testenv]deps}
    Scrapy==1.7.1
    w3lib==1.19.0

[testenv:security]
deps =
    bandit
commands =
    bandit -r {posargs:scrapy_zyte_smartproxy setup.py}

[docs]
changedir = docs
deps =
    -rdocs/requirements.txt

[testenv:docs]
changedir = {[docs]changedir}
deps = {[docs]deps}
commands =
    sphinx-build -nW -b html . {envtmpdir}/html

[testenv:twinecheck]
basepython = python3
deps =
    twine==6.1.0
    build==1.2.2.post1
commands =
    python -m build --sdist
    twine check dist/*
